import os

opcodes = {
    0x0b: ("ASL dp", 4, "const addr = this.getDpAddr(this.readByte(this.state.pc++)); let v = this.readByte(addr); const c = (v & 0x80) !== 0; v = (v << 1) & 0xFF; this.writeByte(addr, v); this.setFlagC(c); this.updateNZ(v);"),
    0x0c: ("ASL abs", 5, "const addr = this.readWord(this.state.pc); this.state.pc += 2; let v = this.readByte(addr); const c = (v & 0x80) !== 0; v = (v << 1) & 0xFF; this.writeByte(addr, v); this.setFlagC(c); this.updateNZ(v);"),
    0x0e: ("TSET1 abs", 6, "const addr = this.readWord(this.state.pc); this.state.pc += 2; const v = this.readByte(addr); this.setFlagZ((this.state.a & v) === 0); this.writeByte(addr, v | this.state.a);"),
    0x17: ("OR A, diy", 6, "const dp = this.readByte(this.state.pc++); const ptr = this.readWord(this.getDpAddr(dp)); const addr = (ptr + this.state.y) & 0xFFFF; this.state.a |= this.readByte(addr); this.updateNZ(this.state.a);"),
    0x36: ("AND A, aby", 5, "const addr = (this.readWord(this.state.pc) + this.state.y) & 0xFFFF; this.state.pc += 2; this.state.a &= this.readByte(addr); this.updateNZ(this.state.a);"),
    0x37: ("AND A, diy", 6, "const dp = this.readByte(this.state.pc++); const ptr = this.readWord(this.getDpAddr(dp)); const addr = (ptr + this.state.y) & 0xFFFF; this.state.a &= this.readByte(addr); this.updateNZ(this.state.a);"),
    0x3b: ("ROL dpx", 5, "const addr = this.getDpAddr((this.readByte(this.state.pc++) + this.state.x) & 0xFF); let v = this.readByte(addr); const carry = (v & 0x80) !== 0; v = ((v << 1) | (this.getFlagC() ? 1 : 0)) & 0xFF; this.writeByte(addr, v); this.setFlagC(carry); this.updateNZ(v);"),
    0x3c: ("ROL A", 2, "const carry = (this.state.a & 0x80) !== 0; this.state.a = ((this.state.a << 1) | (this.getFlagC() ? 1 : 0)) & 0xFF; this.setFlagC(carry); this.updateNZ(this.state.a);"),
    0x47: ("EOR A, dxi", 6, "const dp = this.readByte(this.state.pc++); const addr = this.readWord(this.getDpAddr((dp + this.state.x) & 0xFF)); this.state.a ^= this.readByte(addr); this.updateNZ(this.state.a);"),
    0x4e: ("TCLR1 abs", 6, "const addr = this.readWord(this.state.pc); this.state.pc += 2; const v = this.readByte(addr); this.setFlagZ((this.state.a & v) === 0); this.writeByte(addr, v & ~this.state.a);"),
    0x58: ("EOR dp, imm", 5, "const imm = this.readByte(this.state.pc++); const addr = this.getDpAddr(this.readByte(this.state.pc++)); const val = this.readByte(addr); const res = val ^ imm; this.writeByte(addr, res); this.updateNZ(res);"),
    0x59: ("EOR xi, yi", 5, "const addrX = this.getDpAddr(this.state.x); const addrY = this.getDpAddr(this.state.y); const res = this.readByte(addrX) ^ this.readByte(addrY); this.writeByte(addrX, res); this.updateNZ(res);"),
    0x5a: ("CMPW dp", 4, "const addr = this.getDpAddr(this.readByte(this.state.pc++)); const v = this.readWord(addr); const ya = (this.state.y << 8) | this.state.a; const diff = ya - v; this.setFlagC(ya >= v); this.setFlagZ(diff === 0); this.setFlagN((diff & 0x8000) !== 0);"),
    0x66: ("CMP A, xi", 3, "const addr = this.getDpAddr(this.state.x); const v = this.readByte(addr); const diff = this.state.a - v; this.setFlagC(this.state.a >= v); this.updateNZ(diff & 0xFF);"),
    0x67: ("CMP A, dxi", 6, "const dp = this.readByte(this.state.pc++); const addr = this.readWord(this.getDpAddr((dp + this.state.x) & 0xFF)); const v = this.readByte(addr); const diff = this.state.a - v; this.setFlagC(this.state.a >= v); this.updateNZ(diff & 0xFF);"),
    0x6a: ("AND1 C, !mem.bit", 4, "const word = this.readWord(this.state.pc); this.state.pc += 2; const bit = word >> 13; const addr = word & 0x1FFF; const val = (this.readByte(addr) >> bit) & 1; this.setFlagC(this.getFlagC() && (val === 0));"),
    0x74: ("CMP A, dpx", 4, "const addr = this.getDpAddr((this.readByte(this.state.pc++) + this.state.x) & 0xFF); const v = this.readByte(addr); const diff = this.state.a - v; this.setFlagC(this.state.a >= v); this.updateNZ(diff & 0xFF);"),
    0x76: ("CMP A, aby", 5, "const addr = (this.readWord(this.state.pc) + this.state.y) & 0xFFFF; this.state.pc += 2; const v = this.readByte(addr); const diff = this.state.a - v; this.setFlagC(this.state.a >= v); this.updateNZ(diff & 0xFF);"),
    0x7f: ("RETI", 6, "this.state.psw = this.popByte(); this.state.pc = this.popWord();"),
    0x85: ("ADC A, abs", 4, "const addr = this.readWord(this.state.pc); this.state.pc += 2; const val = this.readByte(addr); const sum = this.state.a + val + (this.getFlagC() ? 1 : 0); this.setFlagH(((this.state.a ^ val ^ sum) & 0x10) !== 0); this.setFlagV(((this.state.a ^ val ^ 0x80) & (this.state.a ^ sum) & 0x80) !== 0); this.setFlagC(sum > 0xFF); this.state.a = sum & 0xFF; this.updateNZ(this.state.a);"),
    0x86: ("ADC A, xi", 3, "const addr = this.getDpAddr(this.state.x); const val = this.readByte(addr); const sum = this.state.a + val + (this.getFlagC() ? 1 : 0); this.setFlagH(((this.state.a ^ val ^ sum) & 0x10) !== 0); this.setFlagV(((this.state.a ^ val ^ 0x80) & (this.state.a ^ sum) & 0x80) !== 0); this.setFlagC(sum > 0xFF); this.state.a = sum & 0xFF; this.updateNZ(this.state.a);"),
    0x87: ("ADC A, dxi", 6, "const dp = this.readByte(this.state.pc++); const addr = this.readWord(this.getDpAddr((dp + this.state.x) & 0xFF)); const val = this.readByte(addr); const sum = this.state.a + val + (this.getFlagC() ? 1 : 0); this.setFlagH(((this.state.a ^ val ^ sum) & 0x10) !== 0); this.setFlagV(((this.state.a ^ val ^ 0x80) & (this.state.a ^ sum) & 0x80) !== 0); this.setFlagC(sum > 0xFF); this.state.a = sum & 0xFF; this.updateNZ(this.state.a);"),
    0x8a: ("EOR1 C, mem.bit", 5, "const word = this.readWord(this.state.pc); this.state.pc += 2; const bit = word >> 13; const addr = word & 0x1FFF; const val = (this.readByte(addr) >> bit) & 1; this.setFlagC(this.getFlagC() !== (val === 1));"),
    0x94: ("ADC A, dpx", 4, "const addr = this.getDpAddr((this.readByte(this.state.pc++) + this.state.x) & 0xFF); const val = this.readByte(addr); const sum = this.state.a + val + (this.getFlagC() ? 1 : 0); this.setFlagH(((this.state.a ^ val ^ sum) & 0x10) !== 0); this.setFlagV(((this.state.a ^ val ^ 0x80) & (this.state.a ^ sum) & 0x80) !== 0); this.setFlagC(sum > 0xFF); this.state.a = sum & 0xFF; this.updateNZ(this.state.a);"),
    0x97: ("ADC A, diy", 6, "const dp = this.readByte(this.state.pc++); const ptr = this.readWord(this.getDpAddr(dp)); const addr = (ptr + this.state.y) & 0xFFFF; const val = this.readByte(addr); const sum = this.state.a + val + (this.getFlagC() ? 1 : 0); this.setFlagH(((this.state.a ^ val ^ sum) & 0x10) !== 0); this.setFlagV(((this.state.a ^ val ^ 0x80) & (this.state.a ^ sum) & 0x80) !== 0); this.setFlagC(sum > 0xFF); this.state.a = sum & 0xFF; this.updateNZ(this.state.a);"),
    0x98: ("ADC dp, imm", 5, "const imm = this.readByte(this.state.pc++); const addr = this.getDpAddr(this.readByte(this.state.pc++)); const val = this.readByte(addr); const sum = val + imm + (this.getFlagC() ? 1 : 0); this.setFlagH(((val ^ imm ^ sum) & 0x10) !== 0); this.setFlagV(((val ^ imm ^ 0x80) & (val ^ sum) & 0x80) !== 0); this.setFlagC(sum > 0xFF); const res = sum & 0xFF; this.writeByte(addr, res); this.updateNZ(res);"),
    0x99: ("ADC xi, yi", 5, "const addrX = this.getDpAddr(this.state.x); const addrY = this.getDpAddr(this.state.y); const valX = this.readByte(addrX); const valY = this.readByte(addrY); const sum = valX + valY + (this.getFlagC() ? 1 : 0); this.setFlagH(((valX ^ valY ^ sum) & 0x10) !== 0); this.setFlagV(((valX ^ valY ^ 0x80) & (valX ^ sum) & 0x80) !== 0); this.setFlagC(sum > 0xFF); const res = sum & 0xFF; this.writeByte(addrX, res); this.updateNZ(res);"),
    0x9f: ("XCN A", 5, "this.state.a = ((this.state.a << 4) | (this.state.a >> 4)) & 0xFF; this.updateNZ(this.state.a);"),
    0xa5: ("SBC A, abs", 4, "const addr = this.readWord(this.state.pc); this.state.pc += 2; const val = this.readByte(addr) ^ 0xFF; const sum = this.state.a + val + (this.getFlagC() ? 1 : 0); this.setFlagH(((this.state.a ^ val ^ sum) & 0x10) !== 0); this.setFlagV(((this.state.a ^ val ^ 0x80) & (this.state.a ^ sum) & 0x80) !== 0); this.setFlagC(sum > 0xFF); this.state.a = sum & 0xFF; this.updateNZ(this.state.a);"),
    0xa6: ("SBC A, xi", 3, "const addr = this.getDpAddr(this.state.x); const val = this.readByte(addr) ^ 0xFF; const sum = this.state.a + val + (this.getFlagC() ? 1 : 0); this.setFlagH(((this.state.a ^ val ^ sum) & 0x10) !== 0); this.setFlagV(((this.state.a ^ val ^ 0x80) & (this.state.a ^ sum) & 0x80) !== 0); this.setFlagC(sum > 0xFF); this.state.a = sum & 0xFF; this.updateNZ(this.state.a);"),
    0xa9: ("SBC dp, dp", 6, "const src = this.getDpAddr(this.readByte(this.state.pc++)); const dst = this.getDpAddr(this.readByte(this.state.pc++)); const val = this.readByte(src) ^ 0xFF; const destVal = this.readByte(dst); const sum = destVal + val + (this.getFlagC() ? 1 : 0); this.setFlagH(((destVal ^ val ^ sum) & 0x10) !== 0); this.setFlagV(((destVal ^ val ^ 0x80) & (destVal ^ sum) & 0x80) !== 0); this.setFlagC(sum > 0xFF); const res = sum & 0xFF; this.writeByte(dst, res); this.updateNZ(res);"),
    0xb5: ("SBC A, abx", 5, "const addr = (this.readWord(this.state.pc) + this.state.x) & 0xFFFF; this.state.pc += 2; const val = this.readByte(addr) ^ 0xFF; const sum = this.state.a + val + (this.getFlagC() ? 1 : 0); this.setFlagH(((this.state.a ^ val ^ sum) & 0x10) !== 0); this.setFlagV(((this.state.a ^ val ^ 0x80) & (this.state.a ^ sum) & 0x80) !== 0); this.setFlagC(sum > 0xFF); this.state.a = sum & 0xFF; this.updateNZ(this.state.a);"),
    0xb6: ("SBC A, aby", 5, "const addr = (this.readWord(this.state.pc) + this.state.y) & 0xFFFF; this.state.pc += 2; const val = this.readByte(addr) ^ 0xFF; const sum = this.state.a + val + (this.getFlagC() ? 1 : 0); this.setFlagH(((this.state.a ^ val ^ sum) & 0x10) !== 0); this.setFlagV(((this.state.a ^ val ^ 0x80) & (this.state.a ^ sum) & 0x80) !== 0); this.setFlagC(sum > 0xFF); this.state.a = sum & 0xFF; this.updateNZ(this.state.a);"),
    0xb9: ("SBC xi, yi", 5, "const addrX = this.getDpAddr(this.state.x); const addrY = this.getDpAddr(this.state.y); const val = this.readByte(addrY) ^ 0xFF; const destVal = this.readByte(addrX); const sum = destVal + val + (this.getFlagC() ? 1 : 0); this.setFlagH(((destVal ^ val ^ sum) & 0x10) !== 0); this.setFlagV(((destVal ^ val ^ 0x80) & (destVal ^ sum) & 0x80) !== 0); this.setFlagC(sum > 0xFF); const res = sum & 0xFF; this.writeByte(addrX, res); this.updateNZ(res);"),
    0xbb: ("INC dpx", 5, "const addr = this.getDpAddr((this.readByte(this.state.pc++) + this.state.x) & 0xFF); const res = (this.readByte(addr) + 1) & 0xFF; this.writeByte(addr, res); this.updateNZ(res);"),
    0xed: ("NOTC", 3, "this.setFlagC(!this.getFlagC());")
}

with open("opcodes_to_add.ts", "w") as f:
    for opcode, data in opcodes.items():
        name, cycles, code = data
        f.write(f"      case 0x{opcode:02X}: {{ // {name}\n")
        # indent code
        f.write("        " + code.replace(";", ";\n        ").strip() + "\n")
        f.write(f"        return {cycles};\n")
        f.write("      }\n")

print("Generated opcodes_to_add.ts")
